logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            certFile = "/sslcerts/docker.localhost+1.pem" # Replace file name as needed
            keyFile = "/sslcerts/docker.localhost+1-key.pem" # Replace file name as needed
    [entryPoints.dashboard]
    address = ":8080"

[docker]
endpoint = "unix://var/run/docker.sock"
watch = true
swarmMode = false
exposedByDefault = false

[api]
dashboard = true
entrypoint = "dashboard"